apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: go-notifications
deploy:
  helm:
    releases:
      - name: go-notifications
        namespace: go-notifications
        createNamespace: true
        chartPath: ../chart-go-notifications/chart
#        remoteChart: catalyst/go-notifications
        version: '>=1.0.0-alpha'
        artifactOverrides:
          image: go-notifications
        imageStrategy:
          helm: {}
        valuesFiles:
          - skaffold-values.yaml
portForward:
  - resourceType: service
    resourceName: go-notifications
    namespace: go-notifications
    port: 6000
    localPort: 6000
